services:
  # mongodb:
  #   image: mongo:latest
  #   hostname: mongodb
  #   container_name: mongodb
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=example
  #   restart: always
  #   volumes:
  #     - ./mongodb:/data/db

  django:
    build: ./backend
    hostname: django
    container_name: django
    ports:
      - "8000:8000"
    # environment:
    #   - MONGO_URI=mongodb://mongodb:27017/mydatabase
    # depends_on:
    #   - mongodb
    
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - mongodb
  #     - backend
  #     - frontend
